-- we don't know how to generate root <with-no-name> (class Root) :(
create table ROLES
(
    ID   INTEGER generated by default as identity (maxvalue 2147483647)
        primary key,
    NAME CHARACTER VARYING(20)
);

create table USUARIO
(
    ID       BIGINT generated by default as identity (maxvalue 9223372036854775807)
        primary key,
    PASSWORD CHARACTER VARYING(255),
    USERNAME CHARACTER VARYING(20)
        constraint UK863N1Y3X0JALATOIR4325EHAL
            unique
);

create table USER_ROLES
(
    USER_ID BIGINT  not null,
    ROLE_ID INTEGER not null,
    primary key (USER_ID, ROLE_ID),
    constraint FK6HDCXIG28SJUX082EKDAE5WNJ
        foreign key (USER_ID) references USUARIO,
    constraint FKH8CIRAMU9CC9Q3QCQIV4UE8A6
        foreign key (ROLE_ID) references ROLES
);

